key:
  defaults:
    name: '&b{crate} Key'
    glow: true
    lore:
    - '&7Right-click {crate} crate to use!'
crates:
  default:
    firework: true
    broadcast: false
    knockback: 0.5
    holograms:
    - '§f{crate}'
    - '§fRight-click with key to use'
    - '§fLeft-click to preview' 